models/User.php
<?php
namespace app\models;
use Yii;
use yii\validators\CompareValidator;
use yii\helpers\ArrayHelper;
    
class User extends \yii\db\ActiveRecord implements \yii\web\IdentityInterface
{

    public $password_repeat;  
    public $authKey;
    public $accessToken;

    public static function tableName()
    {
        return 'users';
    }
    
    public function rules()
    {
        return [
            [['username', 'name'], 'required'],
            [['lang_id', 'group_id','createdBy'], 'integer'],
            [['username', 'name', 'password','email', 'active'], 'string', 'max' => 255],
            [['password'], 'string', 'min' => 6],
            [['group_id'],'default', 'value' => 3],
            [['password_repeat'], 'compare', 'compareAttribute' => 'password', 'message' => 'Пароли не совпадают','skipOnEmpty'=>false],
            [['password_repeat','lastlogin'], 'safe'],
            /**
             *  при регистрации или создании пользователя делаем пароль обязательным полем, 
             *  при обновлении не обязательным у меня выводится при обновлении пустое поле
             *  чтобы поле не перезаписало хэш пароля
             **/
            [['password_repeat','password'], 'required', 'on'=>'register'],
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Логин',
            'name' => 'ФИО',
            'password' => 'Пароль',
            'lang_id' => 'Язык',
            'group_id' => 'Группа',
            'active' => 'Статус',
            'createdBy'=>'Автор',
            'password_repeat'=>'Повторите пароль',
        ];
    }  
    
   /**
    * **************** Связи ******************* 
    * */
    public function getGroups()
    {
       return $this->hasOne(Groups::className(), ['id' => 'group_id']);
    }

    public function getDataGroups() { // все группы видны только superadmin'у
        if (Yii::$app->user->id!=1) 
        {
            $sql = 'SELECT * FROM groups WHERE id!=:id and id!=:id2';
            $models = Groups::findBySql($sql, [':id' => 1,':id2' => 2])->asArray()->all();
        }
        else
        {
            $models = Groups::find([])->asArray()->all();
        }
        return ArrayHelper::map($models, 'id', 'groupname');
    }
    
    
    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'createdBy']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::className(), ['createdBy' => 'id']);
    }
    
      
    /**
     * ************************************************
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
         return static::findOne(['id' => $id]);
    }


    /**
     * Finds user by username
     *
     * @param  string      $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
         return static::findOne(['username' => $username]);
    }


  public function validatePassword($password)
    {
        return $this->password === md5($password);
    }
    
    
   //********  сохранение
    public function beforeSave($insert)
    {
        /**
         *** Пустой пароль мы получим только при обновлении пользователя,
         ** на это имеет право только зарегистрированый пользователь с привилегиями
         *  далее вытаскиваем из базы пароль этого пользователя и присваиваем переменой не шифруя его
         **/ 
        if ($this->password!='')
        {
           return $this->password = $this->hashPassword($this->password);
        }
        else
        {
            $user=User::findOne($this->getId());
           return $this->password = $user->password; 
        }
    }

    public function hashPassword($password)
    {
       return md5($password);
    } 

/*********************/
    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }


    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

 
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use app\models\Groups;
use app\models\AuthAssignment;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\HttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\rbac\ManagerInterface;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }



    /**
     * Lists all User models.  if ( Yii::$app->user->can('update-post', ['model' => $model])) 
     * @return mixed
     */
    public function actionIndex()
    {
       if (Yii::$app->user->can('administrator')) 
       {
            $searchModel = new UserSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            $dataProvider->pagination->pageSizeParam = false;    
        
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');
       }   
            
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
         $model = $this->findModel($id); // пишем так чтобы получить массив записи и проверить я Автор записи или нет
       if ( Yii::$app->user->can('update-user', ['model' => $model]))  
       {
            return $this->render('view', [
                'model' => $model,
            ]);
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');
       }   
            
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
       if (Yii::$app->user->can('create-user')) 
       {
                $model = new User();
                $model->scenario = 'register';
                  
                if ($model->load(Yii::$app->request->post()) ) 
                {    
                     date_default_timezone_set('Asia/Almaty');
                     $model->createdBy=Yii::$app->user->id;
                     if ($model->save())
                     {   
                        //добавление роли при создании записи
                        $auth = Yii::$app->authManager;
                        $role=$this->findAliasgroup($model->group_id);
                        $authorRole = $auth->getRole($role->alias);
                        $auth->assign($authorRole, $model->getId());  
                        return $this->redirect(['index']);
                     }
                     else
                     {
                        return $this->render('create', ['model' => $model]);
                     }   
                }
                else 
                {
                    return $this->render('create', ['model' => $model]);
                }
       } 
       else
       {
        throw new HttpException(403,'Доступ закрыт');
       }
        
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
           $model = $this->findModel($id);

       if ( Yii::$app->user->can('update-user', ['model' => $model]))  
       {
           $old_group=$model->group_id;
             if ($model->load(Yii::$app->request->post()) && $model->save()) 
             { 
                        //добавление роли при обновлении записи
                        $auth = Yii::$app->authManager;
                        /**
                         *  если изменено поле группы то удаляем из таблицы assignment пользователя 
                         *  так как будет записан тот же пользователь, но с другой ролью, иначе будет записан
                         *  один пользователь с двумя видами ролей 
                        **/
                        if ($old_group!=$model->group_id) 
                        {
                            $this->findAssign($id)->delete();  
                            $role=$this->findAliasgroup($model->group_id);
                            $authorRole = $auth->getRole($role->alias);
                            $auth->assign($authorRole, $model->getId());  
                        }
                        
                   return $this->redirect(['index']);
             } else {
                  return $this->render('update', ['model' => $model]);
             }
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');
       }   
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
       $model = $this->findModel($id);// пишем так чтобы получить массив записи и проверить я Автор записи или нет
        
       if ( Yii::$app->user->can('delete-user', ['model' => $model]))  
       {
            $ids= explode(',',$id);
            
            for($i=0;$i<count($ids);$i++)
            {
                $this->findAssign($ids[$i])->delete();  
                $this->findModel($ids[$i])->delete();
            }
            return $this->redirect(['index']);
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');
       }   
            
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
       if (Yii::$app->user->can('administrator')) 
       {
            if (($model = User::findOne($id)) !== null) {
                return $model;
            } else {
                throw new NotFoundHttpException('The requested page does not exist.');
            }
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');
       }   
            
    }
    

    protected function findAliasgroup($id)
    {
       if (Yii::$app->user->can('administrator')) 
       {
            if (($model = Groups::findOne($id)) !== null) {
                return $model;
            } else {
                throw new NotFoundHttpException('The requested page does not exist.');
            }
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');
       }   
            
    }


    protected function findAssign($id)
    {
       if (Yii::$app->user->can('administrator')) 
       {
            if (($model = AuthAssignment::findOne(['user_id' => $id])) !== null) {
                return $model;
            } else {
                throw new NotFoundHttpException('The requested page does not exist.');
            }
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');
       }   
            
    }
    
    
    
}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model app\models\user */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="item-form">
    <?= Html::a('Назад',['index'],['class'=>'goback']) ?>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>
    
    <?= $form->field($model, 'password')->passwordInput(['maxlength' => 255,'value'=>'']) ?>

    <?= $form->field($model, 'password_repeat')->passwordInput(['maxlength' => 255]) ?>

    <?php // $form->field($model, 'lang_id')->textInput() ?>

    <?= $form->field($model, 'group_id')->dropDownList($model->DataGroups,['prompt'=>'- Выберите значение -']) ?>

    <?= $form->field($model, 'active')->checkbox(['class'=>'fch']) ?>

    <?php //$form->field($model, 'createdBy')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => 255]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Добавить<i class="add"></i>' : 'Сохранить<i class="save_ico"></i>', ['class' => $model->isNewRecord ? 'gbtnins' : 'gbtnins']) ?>
        <?= Html::a('Отмена<i class="cancel_ico"></i>', ['user/index'], ['class' => 'gbtncancel ']) ?>

    </div>


    <?php ActiveForm::end(); ?>

</div>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'groups') ?>

    <?php // $form->field($model, 'active') ?>

    <?php // $form->field($model, 'lang_id') ?>

    <?php // echo $form->field($model, 'createdBy') ?>

    <?php // echo $form->field($model, 'email') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\user */

$this->title = 'Добавить пользователя';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title = 'Пользователи';
$this->params['breadcrumbs'][] = $this->title;
Url::remember();
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <div class="form-griedview">
     <div class="tbl-griedview">
       <?= Html::a('Добавить<i class="add"></i>', ['create'], ['class' => 'gbtnins']) ?>
       <?= Html::a('Редактировать<i class="edit"></i>', [null], ['class' => 'gbtnedit','data-lnk'=>'update?id=']) ?>
       <?= Html::a('Удалить<i class="delete"></i>', [null], ['class' => 'gbtncancel','title'=>'удалить','data-confirm'=>'Вы уверены, что хотите удалить этот элемент?','data-method'=>'post','data-lnk'=>'/user/delete?id=']) ?>
       <?= Html::a('Сбросить фильтр<i class="filter"></i>', ['index'], ['class' => 'btnfilter']) ?>
       
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
                [
                  'class' => 'yii\grid\CheckboxColumn',
                  'options'=>['width'=>'1%'],
                  'checkboxOptions' =>['class'=>'chk']
                ],
            //'id',
            'username',
            'name',
            //'active',
                [
                  'attribute'=>'active',     
                  //'name'=>'status1',
                  'format'=>'raw',
                  'value'=> function ($data)  {return $data->active == 1 ?  '<i class="u_active" data-tip="user" data-value="0" data-id="'.$data->id.'"></i>'  : '<i class="u_unactive" data-tip="user" data-value="1" data-id="'.$data->id.'"></i>'; } ,                  
                  'headerOptions'=>['class'=>'w5'],
                  'contentOptions'=>['class'=>'w5'] 
                ],
            //'password',
            //'lang_id',
            //'group_id',
                [
                  'attribute' => 'groups',
                  'label'=>'Группа',
                  'value' => 'groups.groupname',
                  'headerOptions'=>['class'=>'w11'],
                  'contentOptions'=>['class'=>'w11'] 
                ], 
            //'createdBy',
            //'email:email',
                [
                  'attribute' => 'author',
                  'label'=>'Автор',
                  'value' => 'author.username',
                  'headerOptions'=>['class'=>'w11'],
                  'contentOptions'=>['class'=>'w11'] 
                ],
                [
                 'class' => 'yii\grid\ActionColumn',
                 'template' => '{view}',
                 /*'buttons'=>[
                                'update' => function ($url, $model, $key) {
                                        return  Html::a('Update', ['site/index']);
                                    }                 
                            ],*/
                ],
        ],
    ]); ?>
    </div>
  </div>
</div>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\user */

$this->title = 'Обновление пользователя: ' . ' ' . $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $model->username;
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\user */

$this->title = $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>


    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'username',
            'name',
            //'lang_id',
            'groups.groupname',
            //'active',
            [
              'attribute'=>'active',     
              //'name'=>'status1',
              'format'=>'html',
              'value'=> $model->active == 1 ? "активен" : "не активен" ,                  
            ],
            'createdBy',
            'email:email',
        ],
    ]) ?>

</div>