models/Vc.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;
/**
 * This is the model class for table "vc".
 *
 * @property integer $id
 * @property integer $title
 * @property integer $vvagon_id
 * @property integer $sobstvenik_id
 * @property integer $nkotrakt
 *
 * @property Sobstvenik $sobstvenik
 * @property Vvagon $vvagon
 */
class Vc extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vc';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nvg', 'nkotrakt'], 'required'],
            [['nvg', 'vvagon_id', 'sobstvenik_id', 'nkotrakt','createdBy','status'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nvg' => '№ вагона',
            'vvagon_id' => 'Тип вагона',
            'sobstvenik_id' => 'Собственник',
            'nkotrakt' => '№ контракта',
            'createdBy'=>'Автор',
            'status'=>'Статус',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSobstvenik()
    {
        return $this->hasOne(Sobstvenik::className(), ['id' => 'sobstvenik_id']);
    }

    public function getDataSobstvenik() 
    { 
        $models=(new \yii\db\Query)->select('*')->from('sobstvenik')->where('status=1')->all();
        return ArrayHelper::map($models, 'id', 'title');
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVvagon()
    {
        return $this->hasOne(Vvagon::className(), ['id' => 'vvagon_id']);
    }
    
    public function getDataVvagon() 
    { 
        $models=(new \yii\db\Query)->select('*')->from('vvagon')->where('status=1')->all();
        return ArrayHelper::map($models, 'id', 'title');
    }
    
    
}

controllers/VcController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Vc;
use app\models\VcSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\HttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * VcController implements the CRUD actions for vc model.
 */
class VcController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all vc models.
     * @return mixed
     */
    public function actionIndex()
    {
       if ( Yii::$app->user->can('author') )
       {         
            $searchModel = new VcSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');        
       } 

    }


    /**
     * Creates a new vc model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
       if ( Yii::$app->user->can('create-post')) 
       { 
            $model = new Vc();
            if ($model->load(Yii::$app->request->post()) ) 
            {
                $model->createdBy=Yii::$app->user->id;
                $model->status=1;
                if ($model->save())
                {
                    return $this->redirect(['index']);
                }
                else
                {
                   return $this->render('create', ['model' => $model]);
                }            
            }
            else
            {
                return $this->render('create', ['model' => $model]);
            }
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');        
       }              
    
    }

    /**
     * Updates an existing vc model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
       $model = $this->findModel($id);
       if ( Yii::$app->user->can('update-post', ['model' => $model])) 
       { 
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['index']);
            } else {
                return $this->render('update', ['model' => $model]);
            }
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');        
       }         
    }

    /**
     * Deletes an existing vc model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
      $model = $this->findModel($id);
       if ( Yii::$app->user->can('delete-post', ['model' => $model])) 
       {
            $ids= explode(',',$id);
            
            for($i=0;$i<count($ids);$i++)
            {
              $this->findModel($ids[$i])->delete();
            }
            return $this->redirect(['index']);
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');  
       }             
    }

    /**
     * Finds the vc model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return vc the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
       if ( Yii::$app->user->can('author') )
       { 
            if (($model = Vc::findOne($id)) !== null) {
                return $model;
            } else {
                throw new NotFoundHttpException('The requested page does not exist.');
            }
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');  
       }             
    }
}

views/vc/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model app\models\vc */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="item-form">
    <?= Html::a('Назад',['index'],['class'=>'goback']) ?>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nvg')->textInput(['class'=>'form-control small-input']) ?>

    <?= $form->field($model, 'vvagon_id')->dropDownList($model->DataVvagon,['prompt'=>'- Выберите значение -']) ?>

    <?= $form->field($model, 'sobstvenik_id')->dropDownList($model->DataSobstvenik,['prompt'=>'- Выберите значение -']) ?>

    <?= $form->field($model, 'nkotrakt')->textInput(['class'=>'form-control small-input']) ?>

   <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Добавить<i class="add"></i>' : 'Сохранить<i class="save_ico"></i>', ['class' => $model->isNewRecord ? 'gbtnins' : 'gbtnins']) ?>
        <?= Html::a('Отмена<i class="cancel_ico"></i>', ['vc/index'], ['class' => 'gbtncancel ']) ?>
    </div>
    
    <?php ActiveForm::end(); ?>

</div>

views/vc/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\vcSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vc-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nvagon') ?>

    <?= $form->field($model, 'vvagon_id') ?>

    <?= $form->field($model, 'sobstvenik_id') ?>

    <?= $form->field($model, 'nkotrakt') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/vc/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\vc */

$this->title = 'Создать вагон/контракт';
$this->params['breadcrumbs'][] = ['label' => 'Вагон/контракт', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vc-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/vc/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\filters\AccessControl;
/* @var $this yii\web\View */
/* @var $searchModel app\models\vcSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
Url::remember();
$this->title = 'Вагон/контракт';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vc-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

   <div class="form-griedview">
     <div class="tbl-griedview">
       <?= Html::a('Добавить<i class="add"></i>', ['create'], ['class' => 'gbtnins']) ?>
       <?= Html::a('Редактировать<i class="edit"></i>', [null], ['class' => 'gbtnedit','data-lnk'=>'update?id=']) ?>
       <?php if (Yii::$app->user->can('superadmin')) {?>
       <?= Html::a('Удалить<i class="delete"></i>', [null], ['class' => 'gbtncancel','title'=>'удалить','data-confirm'=>'Вы уверены, что хотите удалить этот элемент?','data-method'=>'post','data-lnk'=>'/vc/delete?id=']) ?>
     <?php } else { ?>
       <?= Html::a('Удалить<i class="delete"></i>', [null], ['class' => 'notactive','title'=>'удалить']) ?>
     <?php } ?>
       <?= Html::a('Сбросить фильтр<i class="filter"></i>', ['index'], ['class' => 'btnfilter']) ?>
        
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],
                [
                  'class' => 'yii\grid\CheckboxColumn',
                  'options'=>['width'=>'1%'],
                  'checkboxOptions' =>['class'=>'chk']
                ],               
          //  'id',
            'nvg',
            //'vvagon_id',
                [
                  'attribute' => 'vvagon',
                  'label'=>'Тип вагона',
                  'value' => 'vvagon.title',
                  'headerOptions'=>['class'=>'w16'],
                  'contentOptions'=>['class'=>'w16'],
                  'format'=>'html', 
                  'filter' => Html::activeDropDownList($searchModel,'vvagon_id',$searchModel->DataVvagon,['prompt'=>'- Поле фильтра -'])    //,'class'=>'nostyle'              
                ], 
            //'sobstvenik_id',
                [
                  'attribute' => 'sobstvenik',
                  'label'=>'Собственник',
                  'value' => 'sobstvenik.title',
                  'headerOptions'=>['class'=>'w16'],
                  'contentOptions'=>['class'=>'w16'],
                  'format'=>'html', 
                  'filter' => Html::activeDropDownList($searchModel,'sobstvenik_id',$searchModel->DataSobstvenik,['prompt'=>'- Поле фильтра -'])    //,'class'=>'nostyle'              
                ], 
            //'nkotrakt',
                [
                  'attribute' => 'nkotrakt',
                  'headerOptions'=>['class'=>'w11'],
                  'contentOptions'=>['class'=>'w11'] 
                ], 
                [
                  'format'=>'raw',
                  'attribute' => 'status',
                  'value' => function ($data)  {return $data->status == 1 ?  '<i class="u_active" data-tip="vc" data-value="0" data-id="'.$data->id.'"></i>'  : '<i class="u_unactive" data-tip="vc" data-value="1" data-id="'.$data->id.'"></i>'; } ,
                  'headerOptions'=>['class'=>'w8'],
                  'contentOptions'=>['class'=>'w8'] 
                ],
           // ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
      </div>
    </div>
</div>

views/vc/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\vc */

$this->title = 'Обновить вагон/контракт: ' . ' ' . $model->nvg;
$this->params['breadcrumbs'][] = ['label' => 'Вагон/контракт', 'url' => ['index']];
$this->params['breadcrumbs'][] = $model->nvg;
?>
<div class="vc-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>