models/Sobstvenik.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;
/**
 * This is the model class for table "sobstvenik".
 *
 * @property integer $id
 * @property string $title
 * @property integer $createdBy
 *
 * @property Clean[] $cleans
 * @property Detail[] $details
 * @property Prichina[] $prichinas
 * @property Promiv[] $promivs
 * @property Revizia[] $revizias
 * @property Vagon[] $vagons
 * @property Vc[] $vcs
 */
class Sobstvenik extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sobstvenik';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['createdBy','type','status'], 'integer'],
            [['title'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Наименование',
            'status' => 'Статус',
            'type'=>'Связь',
            'createdBy' => 'Created By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */

    public function getType()
    {
        return $this->hasone(Sobstvenik::className(), ['id' => 'type']);
    }

    public function getDataType() { 
        $models = (new \yii\db\Query())->select('*')->from('sobstvenik')->where('status=1')->all();
        return ArrayHelper::map($models, 'id', 'title');
    }

    public function getCleans()
    {
        return $this->hasMany(Clean::className(), ['sobstvenik_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDetails()
    {
        return $this->hasMany(Detail::className(), ['sobstvenik_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPrichinas()
    {
        return $this->hasMany(Prichina::className(), ['sobstvenik_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPromivs()
    {
        return $this->hasMany(Promiv::className(), ['sobstvenik_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRevizias()
    {
        return $this->hasMany(Revizia::className(), ['sobstvenik_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVagons()
    {
        return $this->hasMany(Vagon::className(), ['sobstvenik_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVcs()
    {
        return $this->hasMany(Vc::className(), ['sobstvenik_id' => 'id']);
    }
}

controllers/SobstvenikController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Sobstvenik;
use app\models\SobstvenikSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\HttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * SobstvenikController implements the CRUD actions for sobstvenik model.
 */
class SobstvenikController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }


    /**
     * Lists all sobstvenik models.
     * @return mixed
     */
    public function actionIndex()
    {
       if ( Yii::$app->user->can('author') )
       {         
            $searchModel = new SobstvenikSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');        
       } 
    }

    /**
     * Displays a single sobstvenik model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
       if ( Yii::$app->user->can('author') )
       { 
            return $this->render('view', ['model' => $this->findModel($id)]);
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');        
       } 
    }

    /**
     * Creates a new sobstvenik model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
       if ( Yii::$app->user->can('create-post')) 
       { 
            $model = new Sobstvenik();
            if ($model->load(Yii::$app->request->post()) ) {
                $model->createdBy=Yii::$app->user->id;
                $model->status=1;
                if ($model->save())
                {
                    return $this->redirect(['index']);
                }
                else
                {
                   return $this->render('create', ['model' => $model]);
                }
            } else {
                return $this->render('create', ['model' => $model]);
            }
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');        
       }             
             
    }

    /**
     * Updates an existing sobstvenik model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
       if ( Yii::$app->user->can('update-post', ['model' => $model])) 
       { 
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['index']);
            } else {
                return $this->render('update', ['model' => $model]);
            }
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');        
       }             
       
    }

    /**
     * Deletes an existing sobstvenik model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
       $model = $this->findModel($id);
       if ( Yii::$app->user->can('delete-post', ['model' => $model])) 
       {
            $ids= explode(',',$id);
            
            for($i=0;$i<count($ids);$i++)
            {
              $this->findModel($ids[$i])->delete();
            }
            return $this->redirect(['index']);
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');  
       }             
    }

    /**
     * Finds the sobstvenik model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return sobstvenik the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
       if ( Yii::$app->user->can('author') )
       { 
            if (($model = Sobstvenik::findOne($id)) !== null) {
                return $model;
            } else {
                throw new NotFoundHttpException('The requested page does not exist.');
            }
       }
       else
       {
              throw new HttpException(403,'Доступ закрыт');  
       }             
    }
}

views/sobstvenik/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model app\models\sobstvenik */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="item-form">
    <?= Html::a('Назад',['index'],['class'=>'goback']) ?>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => 255]) ?>
   
    <?= $form->field($model, 'type')->dropDownList($model->DataType,['prompt'=>'- Выберите связанный пункт -']) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Добавить<i class="add"></i>' : 'Сохранить<i class="save_ico"></i>', ['class' => $model->isNewRecord ? 'gbtnins' : 'gbtnins']) ?>
        <?= Html::a('Отмена<i class="cancel_ico"></i>', ['sobstvenik/index'], ['class' => 'gbtncancel ']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/sobstvenik/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SobstvenikSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="sobstvenik-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/sobstvenik/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\sobstvenik */

$this->title = 'Добавить собственник';
$this->params['breadcrumbs'][] = ['label' => 'Собственник', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="sobstvenik-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/sobstvenik/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\filters\AccessControl;
/* @var $this yii\web\View */
/* @var $searchModel app\models\SobstvenikSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Собственник';
$this->params['breadcrumbs'][] = $this->title;
Url::remember();
?>
<div class="sobstvenik-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

   <div class="form-griedview">
     <div class="tbl-griedview">
       <?= Html::a('Добавить<i class="add"></i>', ['create'], ['class' => 'gbtnins']) ?>
       <?= Html::a('Редактировать<i class="edit"></i>', [null], ['class' => 'gbtnedit','data-lnk'=>'update?id=']) ?>
       <?php if (Yii::$app->user->can('superadmin')) {?>
         <?= Html::a('Удалить<i class="delete"></i>', [null], ['class' => 'gbtncancel','title'=>'удалить','data-confirm'=>'Вы уверены, что хотите удалить этот элемент?','data-method'=>'post','data-lnk'=>'/sobstvenik/delete?id=']) ?>
       <?php } else { ?>
         <?= Html::a('Удалить<i class="delete"></i>', [null], ['class' => 'notactive','title'=>'удалить']) ?>
       <?php } ?>  
       <?= Html::a('Сбросить фильтр<i class="filter"></i>', ['index'], ['class' => 'btnfilter']) ?>
      
       <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                [
                  'class' => 'yii\grid\CheckboxColumn',
                  'options'=>['width'=>'1%'],
                  'checkboxOptions' =>['class'=>'chk']
                ],   

             //   ['class' => 'yii\grid\SerialColumn'],
    
               // 'id',
                'title',
                [
                  'format'=>'raw',
                  'attribute' => 'status',
                  'value' => function ($data)  {return $data->status == 1 ?  '<i class="u_active" data-tip="sobstvenik" data-value="0" data-id="'.$data->id.'"></i>'  : '<i class="u_unactive" data-tip="sobstvenik" data-value="1" data-id="'.$data->id.'"></i>'; } ,
                  'headerOptions'=>['class'=>'w8'],
                  'contentOptions'=>['class'=>'w8'] 
                ],  
               // ['class' => 'yii\grid\ActionColumn'],
            ],
        ]); ?>
      </div>
    </div>
</div>

views/sobstvenik/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\sobstvenik */

$this->title = 'Обновить собственник: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Собственник', 'url' => ['index']];
$this->params['breadcrumbs'][] = $model->title;
?>
<div class="sobstvenik-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/sobstvenik/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\sobstvenik */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Sobstveniks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="sobstvenik-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
        ],
    ]) ?>

</div>